-- ==========================================================================
-- x4n_game_data.lua -- Game Data Lookup Tables
-- ==========================================================================
-- Auto-generated by scripts/generate_game_data.ps1
-- Source: sdk/x4_manual_types.h, reference/game/libraries/
--
-- DO NOT EDIT -- regenerate with: .\scripts\generate_game_data.ps1
-- ==========================================================================

-- Room macro name -> roomtype string.
-- When a macro is used by multiple room definitions (e.g. managersoffice as
-- both "manager" and "factionrep"), the primary (non-factionrep) type is listed.
x4n_ROOM_MACRO_TO_TYPE = {
    ["room_bor_managersoffice_01_macro"] = "manager",
    ["room_bor_throneroom_01_macro"] = "bar",
    ["room_gen_bar_01_macro"] = "bar",
    ["room_gen_boronoffice_01_macro"] = "manager",
    ["room_gen_casino_01_macro"] = "casino",
    ["room_gen_common_01_macro"] = "crewquarters",
    ["room_gen_detentioncell_01_macro"] = "prison",
    ["room_gen_embassy_01_macro"] = "embassy",
    ["room_gen_factionrepresentative_01_macro"] = "factionrep",
    ["room_gen_generator_01_macro"] = "generatorroom",
    ["room_gen_infrastructureoffice_01_macro"] = "infrastructure",
    ["room_gen_intelligenceoffice_01_macro"] = "intelligenceoffice",
    ["room_gen_livingroom_01_macro"] = "livingroom",
    ["room_gen_livingroomshadyguy_01_macro"] = "livingroom",
    ["room_gen_managersoffice_01_macro"] = "manager",
    ["room_gen_playeroffice_01_macro"] = "playeroffice",
    ["room_gen_securityoffice_01_macro"] = "security",
    ["room_gen_serverroom_01_macro"] = "serverroom",
    ["room_gen_service_01_macro"] = "serviceroom",
    ["room_gen_trafficcontrol_01_macro"] = "trafficcontrol",
    ["room_gen_war_01_macro"] = "warroom",
    ["room_par_managersoffice_01_macro"] = "manager",
    ["room_spl_managersoffice_01_macro"] = "manager",
    ["room_tel_managersoffice_01_macro"] = "manager",
    ["room_ter_managersoffice_01_macro"] = "manager",
}

-- Set of corridor macros.
x4n_CORRIDOR_MACROS = {
    ["room_arg_corridor_01_macro"] = true,
    ["room_arg_corridor_02_macro"] = true,
    ["room_arg_corridor_03_macro"] = true,
    ["room_arg_corridor_04_macro"] = true,
    ["room_arg_corridor_05_macro"] = true,
    ["room_arg_corridor_06_macro"] = true,
    ["room_bor_corridor_01_macro"] = true,
    ["room_bor_corridor_02_macro"] = true,
    ["room_par_corridor_01_macro"] = true,
    ["room_spl_corridor_01_macro"] = true,
    ["room_tel_corridor_01_macro"] = true,
    ["room_ter_corridor_01_macro"] = true,
}

-- Roomtype -> enum index (from X4RoomType in x4_manual_types.h).
x4n_ROOMTYPE_INDEX = {
    bar = 0,
    casino = 1,
    corridor = 2,
    crewquarters = 3,
    embassy = 4,
    factionrep = 5,
    generatorroom = 6,
    infrastructure = 7,
    intelligenceoffice = 8,
    livingroom = 9,
    manager = 10,
    office = 11,
    playeroffice = 12,
    prison = 13,
    security = 14,
    serverroom = 15,
    serviceroom = 16,
    shiptradercorner = 17,
    tradercorner = 18,
    trafficcontrol = 19,
    warroom = 20,
    none = 21,
}

-- Returns true if the macro is a known corridor.
function x4n_is_corridor(macro)
    return x4n_CORRIDOR_MACROS[macro] == true
end

-- Returns roomtype_string, roomtype_index or nil, -1 if unknown.
function x4n_lookup_room(macro)
    local rtype = x4n_ROOM_MACRO_TO_TYPE[macro]
    if rtype then
        return rtype, (x4n_ROOMTYPE_INDEX[rtype] or -1)
    end
    return nil, -1
end
