<#
.SYNOPSIS
    Generate version_db metadata (func_history.json, type_changes.json).

.DESCRIPTION
    Tracks per-function and per-struct lifecycle across game versions.
    Reads the generated SDK headers (x4_game_func_list.inc, x4_game_types.h)
    directly and diffs against existing JSON history files.

    Standalone pipeline step — run after generate_headers.ps1.

.PARAMETER GameVersion
    Override the version key used in func_history.json and type_changes.json.
    When omitted, the version is read from reference/game/VERSION.
    Passed automatically by update_references.ps1 when -VersionSuffix is used.

.EXAMPLE
    .\scripts\generate_version_db.ps1
#>
param(
    [string]$GameVersion
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent

# Input files (generated by generate_headers.ps1)
$funcListFile = Join-Path $repoRoot 'sdk\x4_game_func_list.inc'
$typesFile    = Join-Path $repoRoot 'sdk\x4_game_types.h'
$versionFile  = Join-Path $repoRoot 'reference\game\VERSION'

# Output files
$versionDbDir   = Join-Path $repoRoot 'native\version_db'
$FuncHistoryPath = Join-Path $versionDbDir 'func_history.json'
$TypeChangesPath = Join-Path $versionDbDir 'type_changes.json'

if (-not (Test-Path $versionDbDir)) { New-Item -ItemType Directory -Path $versionDbDir -Force | Out-Null }

# Validate prerequisites
if (-not (Test-Path $funcListFile)) {
    Write-Error "sdk/x4_game_func_list.inc not found. Run generate_headers.ps1 first."
    exit 1
}
if (-not (Test-Path $typesFile)) {
    Write-Error "sdk/x4_game_types.h not found. Run generate_headers.ps1 first."
    exit 1
}

if (-not $GameVersion) {
    $GameVersion = if (Test-Path $versionFile) { (Get-Content $versionFile -Raw).Trim() } else { 'unknown' }
}

Write-Host "Generating version metadata..." -ForegroundColor Green

# ---------------------------------------------------------------------------
# Helper: Reformat JSON with consistent 4-space indentation
# (PowerShell 5.1's ConvertTo-Json produces non-standard deep nesting)
# ---------------------------------------------------------------------------
function Format-Json([string]$json) {
    $indent = 0
    $result = [System.Text.StringBuilder]::new($json.Length)
    $inString = $false
    $prevChar = [char]0

    foreach ($char in $json.ToCharArray()) {
        if ($char -eq '"' -and $prevChar -ne '\') { $inString = -not $inString }
        if ($inString) { [void]$result.Append($char); $prevChar = $char; continue }

        switch ($char) {
            '{' { [void]$result.Append("{`n"); $indent++; [void]$result.Append('    ' * $indent) }
            '[' { [void]$result.Append("[`n"); $indent++; [void]$result.Append('    ' * $indent) }
            '}' { $indent--; [void]$result.Append("`n"); [void]$result.Append('    ' * $indent); [void]$result.Append('}') }
            ']' { $indent--; [void]$result.Append("`n"); [void]$result.Append('    ' * $indent); [void]$result.Append(']') }
            ',' { [void]$result.Append(",`n"); [void]$result.Append('    ' * $indent) }
            ':' { [void]$result.Append(': ') }
            default {
                if (-not [char]::IsWhiteSpace($char)) { [void]$result.Append($char) }
            }
        }
        $prevChar = $char
    }
    return $result.ToString()
}

# ===========================================================================
# Parse current function set from .inc file
# ===========================================================================

$currentFuncs = [ordered]@{}  # name -> "retType (params)"
foreach ($line in (Get-Content $funcListFile)) {
    if ($line -match '^X4_FUNC\(\s*(.+?),\s*(\w+),\s*\((.+?)\)\s*\)') {
        $currentFuncs[$Matches[2]] = "$($Matches[1].Trim()) ($($Matches[3].Trim()))"
    }
}
Write-Host "  $($currentFuncs.Count) functions in .inc"

# ===========================================================================
# Parse current struct set from types header
# ===========================================================================

$currentStructs = [ordered]@{}  # name -> body fingerprint
$typesLines = Get-Content $typesFile
$state = 'idle'
$structAccum = [System.Collections.Generic.List[string]]::new()

foreach ($line in $typesLines) {
    if ($state -eq 'in_struct') {
        $structAccum.Add($line)
        if ($line -match '}\s*(\w+)\s*;') {
            $sname = $Matches[1]
            $state = 'idle'
            $allLines = $structAccum.ToArray()
            $bodyLines = if ($allLines.Count -gt 2) {
                $allLines[1..($allLines.Count - 2)]
            } else { @() }
            $body = ($bodyLines | ForEach-Object { $_.Trim() }) -join ' '
            $currentStructs[$sname] = $body
            $structAccum.Clear()
        }
        continue
    }

    # Single-line struct
    if ($line -match '^\s*typedef\s+struct\s*\{.*}\s*(\w+)\s*;') {
        $sname = $Matches[1]
        $body = $line -replace '^\s*typedef\s+struct\s*\{\s*', '' -replace '\s*}\s*\w+\s*;\s*$', ''
        $currentStructs[$sname] = $body
        continue
    }

    # Multi-line struct start
    if ($line -match '^\s*typedef\s+struct\s*[\{]?\s*$') {
        $state = 'in_struct'
        $structAccum.Clear()
        $structAccum.Add($line)
    }
}
Write-Host "  $($currentStructs.Count) structs in types header"

# ===========================================================================
# func_history.json
# ===========================================================================

$funcHistory = $null
if (Test-Path $FuncHistoryPath) {
    try {
        $funcHistory = Get-Content $FuncHistoryPath -Raw | ConvertFrom-Json
    } catch {
        Write-Warning "Could not parse existing func_history.json, regenerating"
    }
}

if (-not $funcHistory) {
    # Baseline — all current functions tagged with this version
    $funcHistory = [PSCustomObject]@{
        schema_version = 1
        baseline       = $GameVersion
        versions       = @($GameVersion)
        functions      = [ordered]@{}
    }
    foreach ($fname in ($currentFuncs.Keys | Sort-Object)) {
        $funcHistory.functions[$fname] = [PSCustomObject]@{ added = $GameVersion }
    }
} else {
    # Incremental — diff current .inc against existing history
    $existingVersions = @($funcHistory.versions)
    if ($GameVersion -notin $existingVersions) {
        $funcHistory.versions = $existingVersions + @($GameVersion)
    }

    $funcEntries = [ordered]@{}
    foreach ($prop in $funcHistory.functions.PSObject.Properties) {
        $entry = [ordered]@{ added = $prop.Value.added }
        if ($prop.Value.removed)           { $entry['removed']           = $prop.Value.removed }
        if ($prop.Value.signature_changed) { $entry['signature_changed'] = $prop.Value.signature_changed }
        $funcEntries[$prop.Name] = $entry
    }

    $previousFuncSet = [System.Collections.Generic.HashSet[string]]::new([string[]]@($funcEntries.Keys))
    $currentFuncSet  = [System.Collections.Generic.HashSet[string]]::new([string[]]@($currentFuncs.Keys))

    $addedCount = 0
    foreach ($fname in ($currentFuncs.Keys | Sort-Object)) {
        if (-not $previousFuncSet.Contains($fname)) {
            $funcEntries[$fname] = [ordered]@{ added = $GameVersion }
            $addedCount++
        }
    }

    $removedCount = 0
    foreach ($fname in @($funcEntries.Keys)) {
        if (-not $currentFuncSet.Contains($fname) -and -not $funcEntries[$fname].Contains('removed')) {
            $funcEntries[$fname]['removed'] = $GameVersion
            $removedCount++
        }
    }

    $funcHistory.functions = $funcEntries

    if ($addedCount -gt 0 -or $removedCount -gt 0) {
        Write-Host "  Func diff: +$addedCount added, -$removedCount removed" -ForegroundColor Yellow
    }
}

$historyJson = Format-Json ($funcHistory | ConvertTo-Json -Depth 4 -Compress)
[System.IO.File]::WriteAllText($FuncHistoryPath, $historyJson)
$funcCount = if ($funcHistory.functions -is [System.Collections.IDictionary]) { $funcHistory.functions.Count } else { @($funcHistory.functions.PSObject.Properties).Count }
$historySize = [math]::Round((Get-Item $FuncHistoryPath).Length / 1024, 1)
Write-Host "  func_history.json  ${historySize} KB ($funcCount functions)"

# ===========================================================================
# type_changes.json
# ===========================================================================

$typeChanges = $null
if (Test-Path $TypeChangesPath) {
    try {
        $typeChanges = Get-Content $TypeChangesPath -Raw | ConvertFrom-Json
    } catch {
        Write-Warning "Could not parse existing type_changes.json, regenerating"
    }
}

if (-not $typeChanges) {
    # Baseline
    $typeChanges = [PSCustomObject]@{
        schema_version = 1
        baseline       = $GameVersion
        versions       = @($GameVersion)
        struct_count   = $currentStructs.Count
        structs        = [ordered]@{}
    }
    foreach ($sname in ($currentStructs.Keys | Sort-Object)) {
        $typeChanges.structs[$sname] = [PSCustomObject]@{
            added       = $GameVersion
            fingerprint = $currentStructs[$sname]
        }
    }
} else {
    # Incremental
    $existingVersions = @($typeChanges.versions)
    if ($GameVersion -notin $existingVersions) {
        $typeChanges.versions = $existingVersions + @($GameVersion)
    }
    $typeChanges.struct_count = $currentStructs.Count

    $structEntries = [ordered]@{}
    foreach ($prop in $typeChanges.structs.PSObject.Properties) {
        $entry = [ordered]@{
            added       = $prop.Value.added
            fingerprint = $prop.Value.fingerprint
        }
        if ($prop.Value.removed) { $entry['removed'] = $prop.Value.removed }
        if ($prop.Value.changes) { $entry['changes'] = @($prop.Value.changes) }
        $structEntries[$prop.Name] = $entry
    }

    $addedStructs   = 0
    $removedStructs = 0
    $changedStructs = [System.Collections.Generic.List[string]]::new()

    foreach ($sname in $currentStructs.Keys) {
        if (-not $structEntries.Contains($sname)) {
            $structEntries[$sname] = [ordered]@{
                added       = $GameVersion
                fingerprint = $currentStructs[$sname]
            }
            $addedStructs++
        }
    }

    $currentStructSet = [System.Collections.Generic.HashSet[string]]::new([string[]]@($currentStructs.Keys))
    foreach ($sname in @($structEntries.Keys)) {
        if (-not $currentStructSet.Contains($sname) -and -not $structEntries[$sname].Contains('removed')) {
            $structEntries[$sname]['removed'] = $GameVersion
            $removedStructs++
        }
    }

    foreach ($sname in $currentStructs.Keys) {
        if ($structEntries.Contains($sname) -and $structEntries[$sname]['fingerprint'] -ne $currentStructs[$sname]) {
            if (-not $structEntries[$sname].Contains('changes')) {
                $structEntries[$sname]['changes'] = @()
            }
            $structEntries[$sname]['changes'] += "$GameVersion"
            $structEntries[$sname]['fingerprint'] = $currentStructs[$sname]
            $changedStructs.Add($sname)
        }
    }

    $typeChanges.structs = $structEntries

    if ($addedStructs -gt 0 -or $removedStructs -gt 0 -or $changedStructs.Count -gt 0) {
        Write-Host "  Struct diff: +$addedStructs added, -$removedStructs removed, ~$($changedStructs.Count) changed" -ForegroundColor Yellow
    }
    if ($changedStructs.Count -gt 0) {
        Write-Warning "Structs with layout changes (extensions using these must recompile):"
        foreach ($sname in $changedStructs) { Write-Warning "  $sname" }
    }
}

$typeJson = Format-Json ($typeChanges | ConvertTo-Json -Depth 4 -Compress)
[System.IO.File]::WriteAllText($TypeChangesPath, $typeJson)
$structTracked = if ($typeChanges.structs -is [System.Collections.IDictionary]) { $typeChanges.structs.Count } else { @($typeChanges.structs.PSObject.Properties).Count }
$typeSize = [math]::Round((Get-Item $TypeChangesPath).Length / 1024, 1)
Write-Host "  type_changes.json  ${typeSize} KB ($structTracked structs)"
Write-Host ""
